### ISSUE TITLE
ElyWing

### ISSUE THREAD

**Issue by NycuRO** [jojoe77777/Slapper#10]
Not work with ElyWing..

**Comment by Sandertv** [comment]
Note `The new home of Slapper, the NPC plugin for PocketMine/Genisys.`

**Comment by NycuRO** [comment]
@Sandertv I'm fixed error in PR

**Comment by dktapps** [comment]
Not supported, Elywing copy-paste so many things they don't maintain anything like a workable API. 🖕 to them.

**Comment by NycuRO** [comment]
@dktapps I'm using for Elytra support, for blocks 1.0.0 and SUPPORT 1.0.0 BECAUSE YOU JUST DON'T CARE ABOUT THIS UPDATE!

**Comment by NycuRO** [comment]
GENISYS 0.16.2, PMMP 0.16.1 ! YOUR REPOSITORY! MiNET updated ,Nukkit Updated, ElyWing Updated !!!!

**Comment by dktapps** [comment]
Yes, and it's ludicrously unstable.

I don't know if you even bothered to look at the pmmp repository, but there is a fully functional **development** branch there. However, we don't lie to people and stick big fake "stable" labels on things and trick people into thinking it's safe to use.
