### ISSUE TITLE
FallingSand text don't show if you are 4-5 block away from it

### ISSUE THREAD

**Issue by XDqrkneZ** [jojoe77777/Slapper#100]
Spawn a fallingsand
/slapper add fallingsand test
/slapper edit 16 blockid 0
move 4-5 blocks away from it and it'll disappear/go invisible
move closer to it and it will show again.
I'm using the Slapper for ALPHA8 and PMMP ALpha8

**Comment by jojoe77777** [comment]
#95

Also, the latest is ALPHA9.
