### ISSUE TITLE
Doesn't Work With ALPHA9

### ISSUE THREAD

**Issue by PotatoeTrainYT** [jojoe77777/Slapper#104]
I Updated My Servera To ALPHA9 So I Could Use Enchants, When I Updated Them I Realised That All My Slappers Had Despawned! So I Went To Spawn Them Back, And They Would Be Invisible And You Can't Interact With Them. Please Fix This Issues

**Comment by jojoe77777** [comment]
During your update process, you must have started the server without Slapper updated.
