### ISSUE TITLE
This plugin corupted my world and all. Thanks. Watch error.

### ISSUE THREAD

**Issue by RoofyManStar** [jojoe77777/Slapper#114]
```


2017-12-17 [12:46:13] [Server thread/CRITICAL]: InvalidArgumentException: "Unknown NBT tag type 167" (EXCEPTION) in "src/pocketmine/nbt/NBT" at line 105

2017-12-17 [12:46:13] [Server thread/CRITICAL]: InvalidArgumentException: "Unknown NBT tag type 194" (EXCEPTION) in "src/pocketmine/nbt/NBT" at line 105
```

I enter 4-5 times, and i get this.

**Comment by robske110** [comment]
1) What version of Slapper are you using.
2) What EXACT version of pmmp are you using (build num/commit hash)

**Comment by RoofyManStar** [comment]
1 . https://github.com/jojoe77777/Slapper/commit/a4a883953ff8dae35e45bcf39359a44f6b1042ec
2. [Server thread/INFO]: This server is running PocketMine-MP 1.7dev-494 「[REDACTED]」 implementing API version 3.0.0-ALPHA10 for Minecraft: PE v1.2.6 (protocol version 150)

**Comment by jojoe77777** [comment]
@RoofyManStar That's not a commit hash

**Comment by RoofyManStar** [comment]
http://www.mediafire.com/file/55d9ull0bb59p6c/server.log

My server.log

**Comment by dktapps** [comment]
Possibly related issue: https://github.com/pmmp/PocketMine-NBT/issues/34

Could you provide a copy of the corrupted world?

**Comment by artulloss** [comment]
Same issue here, only the chunk surrounding the slapper was corrupted

**Comment by dktapps** [comment]
Due to corruption issues fixed in PocketMine-NBT and the lack of response on this issue, I'm going to close it.
