### ISSUE TITLE
How do you insert?

### ISSUE THREAD

**Issue by inaughtysteve** [jojoe77777/Slapper#116]
I cannot seem to be able to insert the plugin into my pocketmine 3.0.0 ALPHA 10 server. Is there a .phar file I am missing? Because that seems to be the only file type my server works with.

**Comment by jojoe77777** [comment]
Option 1: Install DevTools and run the plugin from source
Option 2: Use the phar I just compiled & released for ALPHA10: https://github.com/jojoe77777/Slapper/releases/download/1.3.7/Slapper_v1.3.7.phar

**Comment by inaughtysteve** [comment]
Thanks
