### ISSUE TITLE
edits dont stay after a server restart

### ISSUE THREAD

**Issue by FienixEC** [jojoe77777/Slapper#121]
Whenever i use /slapper edit xxx name (or any edit command) it resets after a server restart, i noticed this after spawning a slapper with "TEST" as name, i then edited the name to "Slapper" on server restart it changed back to "TEST". also noticed this when adding commands to the slapper, after restart, the commands were gone. Any info on this? or am i missing something?

This server is running PocketMine-MP 1.7dev-554 ã€Œ[REDACTED]ã€ implementing API version 3.0.0-ALPHA10 for Minecraft: PE v1.2.7 (protocol version 160)

**Comment by FienixEC** [comment]
Seems to happen with certain commands as i just found out, slappers with a certain command i added was working before a server restart, now they are not and when i do /slapper edit <id> listcommands nothing happens....pls help

**Comment by dktapps** [comment]
This should be fixed in 886580b6c3b6c434177024a1e42e65da3c4ab209.
