### ISSUE TITLE
An Unknown Error Occured

### ISSUE THREAD

**Issue by thefuncraftmcpe** [jojoe77777/Slapper#128]
I can install this plugin on my server easily. When I do /slapper create zombie Hi, it says "An Unknown Error Occurred". Even if I use other slapper commands correctly, it will always say "An Unknown Error Occurred". Please help as the slappers are not working!

**Comment by jojoe77777** [comment]
Please provide the contents of your console when the error occurs

**Comment by BajanVlogs** [comment]
29.01 20:52:34 [Server] Server thread/CRITICAL Unhandled exception executing command 'slapper spawn human (!) Tap Me To Go To Spawn (!)' in slapper: Call to undefined method pocketmine\Player::getSkinData()
29.01 20:52:34 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\Player::getSkinData()" (EXCEPTION) in "Slapper.phar/src/slapper/Main" at line 675

**Comment by BajanVlogs** [comment]
29.01 23:38:21 [Server] Server thread/CRITICAL Unhandled exception executing command 'slapper spawn fallingsand t' in slapper: Call to undefined method slapper\entities\other\SlapperFallingSand::setDataProperty()
29.01 23:38:21 [Server] Server thread/CRITICAL Error: "Call to undefined method slapper\entities\other\SlapperFallingSand::setDataProperty()" (EXCEPTION) in "Slapper-master/src/slapper/entities/SlapperEntity" at line 48

**Comment by BajanVlogs** [comment]
Its like this for every single one

**Comment by jojoe77777** [comment]
This plugin is not designed for latest development branches, it's designed for the ALPHA10 release (1.7dev-516 at the time of writing).
