### ISSUE TITLE
Name Tags Color Issue

### ISSUE THREAD

**Issue by RenderedPix** [jojoe77777/Slapper#142]
Name Tags cannot be colored using `&`
------------------------
Reproducing Steps:
1: `/slapper create human &eTest`
------------------------
Windows 10 Edition cannot do the color symbol, because it is on a pc. Will be needed to copy and paste.
Plugin not caught up to Minecraft PE updates?

**Comment by RenderedPix** [comment]
I have tried rejoining and it did NOT work.

**Comment by jojoe77777** [comment]
https://github.com/jojoe77777/Slapper/blob/master/src/slapper/Main.php#L609
Use `{color}`
