### ISSUE TITLE
Please Update To 3.0.0ALPHA12 

### ISSUE THREAD

**Issue by joshuasing** [jojoe77777/Slapper#145]
Please Update To 3.0.0ALPHA12 for PMMP

**Comment by jojoe77777** [comment]
https://github.com/jojoe77777/Slapper/commit/b1505bfacccbb807f392d006d15e4c77f6a47948

**Comment by dktapps** [comment]
PleasE UPDaTe to 3.0.0ALPHa12 FOR pmmP
