### ISSUE TITLE
cant spawn mob (more information)

### ISSUE THREAD

**Issue by treehousemc1** [jojoe77777/Slapper#148]
When i do "/slapper (spawn/create) (mob) (name)" it show An unknown error occurred while attempting to perform this command. I have tried this on API 11-12 still not working.

**Comment by treehousemc1** [comment]
Error display in console:

01.05 08:36:54 [Server] Server thread/CRITICAL Unhandled exception executing command 'slapper create zombie 1' in slapper: Argument 2 passed to pocketmine\entity\DataPropertyManager::setFloat() must be of the type float, null given, called in phar:///custom.phar/src/pocketmine/entity/Entity.php on line 534
01.05 08:36:54 [Server] Server thread/CRITICAL TypeError: "Argument 2 passed to pocketmine\entity\DataPropertyManager::setFloat() must be of the type float, null given, called in phar:///custom.phar/src/pocketmine/entity/Entity.php on line 534" (EXCEPTION) in "src/pocketmine/entity/DataPropertyManager" at line 115
01.05 08:36:54 [Server] Server thread/DEBUG #0 src/pocketmine/entity/Entity(534): pocketmine\entity\DataPropertyManager->setFloat(integer 53, NULL )
01.05 08:36:54 [Server] Server thread/DEBUG #1 Slapper.phar/src/slapper/entities/SlapperEntity(18): pocketmine\entity\Entity->__construct(pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object)
01.05 08:36:54 [Server] Server thread/DEBUG #2 src/pocketmine/entity/Entity(278): slapper\entities\SlapperEntity->__construct(pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object)
01.05 08:36:54 [Server] Server thread/DEBUG #3 Slapper.phar/src/slapper/Main(638): pocketmine\entity\Entity::createEntity(string SlapperZombie, pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object)
01.05 08:36:54 [Server] Server thread/DEBUG #4 src/pocketmine/command/PluginCommand(58): slapper\Main->onCommand(pocketmine\Player object, pocketmine\command\PluginCommand object, string slapper, array Array())
01.05 08:36:54 [Server] Server thread/DEBUG #5 src/pocketmine/command/SimpleCommandMap(258): pocketmine\command\PluginCommand->execute(pocketmine\Player object, string slapper, array Array())
01.05 08:36:54 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1946): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string slapper create zombie 1)
01.05 08:36:54 [Server] Server thread/DEBUG #7 src/pocketmine/Player(2188): pocketmine\Server->dispatchCommand(pocketmine\Player object, string slapper create zombie 1)
01.05 08:36:54 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(222): pocketmine\Player->chat(string /slapper create zombie 1)
01.05 08:36:54 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
01.05 08:36:54 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
01.05 08:36:54 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/protocol/BatchPacket(114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
01.05 08:36:54 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
01.05 08:36:54 [Server] Server thread/DEBUG #13 src/pocketmine/Player(3031): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
01.05 08:36:54 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/RakLibInterface(153): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
01.05 08:36:54 [Server] Server thread/DEBUG #15 vendor/pocketmine/raklib/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 118.100.243.96 17389, raklib\protocol\EncapsulatedPacket object, integer 0)
01.05 08:36:54 [Server] Server thread/DEBUG #16 src/pocketmine/network/mcpe/RakLibInterface(94): raklib\server\ServerHandler->handlePacket()
01.05 08:36:54 [Server] Server thread/DEBUG #17 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
01.05 08:36:54 [Server] Server thread/DEBUG #18 src/pocketmine/Server(2495): pocketmine\network\Network->processInterfaces()
01.05 08:36:54 [Server] Server thread/DEBUG #19 src/pocketmine/Server(2243): pocketmine\Server->tick()
01.05 08:36:54 [Server] Server thread/DEBUG #20 src/pocketmine/Server(2119): pocketmine\Server->tickProcessor()
01.05 08:36:54 [Server] Server thread/DEBUG #21 src/pocketmine/Server(1701): pocketmine\Server->start()
01.05 08:36:54 [Server] Server thread/DEBUG #22 src/pocketmine/PocketMine(305): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
01.05 08:36:54 [Server] Server thread/DEBUG #23 /custom.phar(1): require(string phar:///custom.phar/src/pocketmine/PocketMine.php)

**Comment by dktapps** [comment]
your slapper version is out of date.
