### ISSUE TITLE
Error: Call to undefined method slapper\entities\SlapperHuman::getServer()

### ISSUE THREAD

**Issue by Callum9966** [jojoe77777/Slapper#15]
Error: Call to undefined method slapper\entities\SlapperHuman::getServer()

**Comment by Sandertv** [comment]
I have already reported this and fixed it. Please try the latest version.

**Comment by Callum9966** [comment]
I'm using ElyWing 1.0, anyway to fix it for ElyWing?

**Comment by dktapps** [comment]
🤦‍♂️ yes, the solution is don't use Elywing.

**Comment by Callum9966** [comment]
ElyWing is the only software on 1.0 right now

**Comment by Sandertv** [comment]
Uhm... No. PocketMine has already updated quite some time ago, and without PocketMine Elywing wouldn't be 1.0.0 at all. Genisys has a 1.0.0 branch, but I think there's no phar file for that just yet.

**Comment by dktapps** [comment]
have you been living under a rock or something?

**Comment by jojoe77777** [comment]
Elywing is not supported

**Comment by legoboy0215** [comment]
@Callum9966 There has been a PMMP 1.0 build for quite a long time.

**Comment by Callum9966** [comment]
Can you email it to me
