### ISSUE TITLE
Moo.

### ISSUE THREAD

**Issue by ghost** [jojoe77777/Slapper#151]
As of ALPHA12,  1.4 pmmp it seems that you can no longer place any slappers that are not human.

Horses, cows, sheep, pigs cause the message "an unknown error has occurred" to pop up in-game chat.

Unfortunately this is happening on a server that i don't have console access so i'm unable to give any more details regarding the issue.

**Comment by dktapps** [comment]
make sure you're using the release build (1001) and not a development build. Slapper may break on the newest development builds.

**Comment by jojoe77777** [comment]
Can't reproduce
