### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by NGGNewGen** [jojoe77777/Slapper#153]
~- Slappers that can walk to destinations with set points on the server~
~- Slappers that can sneak then unsneak with a time interval between the two~
- Slappers that have customized messages above their heads 

These are just a few suggestions that could (hopefully) be implemented :)

**Comment by jojoe77777** [comment]
Slapper is an NPC plugin, not a walking entities plugin.
> Slappers that have customized messages above their heads
What do you mean by this? You mean variables per-player?

**Comment by NGGNewGen** [comment]
Okay, sorry heh i just have some weird ideas :P
and no i mean a message above the entities head that changes every x seconds to another customized message, kind of like avengetech or PHCCrafters.

**Comment by jojoe77777** [comment]
That won't be added to Slapper
