### ISSUE TITLE
Minecraft: PE v1.5.0 -PocketMine-MP 4.0.0+dev.1242

### ISSUE THREAD

**Issue by raidksh** [jojoe77777/Slapper#165]

**Comment by dktapps** [comment]
as you can clearly see [here](https://github.com/jojoe77777/Slapper/blob/master/plugin.yml#L6), 4.0.0 is not supported.

**Comment by raidksh** [comment]
Do you have any updates planned?

**Comment by SOF3** [comment]
@raidksh Do you have any downdates planned?

**Comment by LeronDoesGaming** [comment]
@SOF3 Do you have any sidedates planned?

**Comment by dktapps** [comment]
@LeronDoesGaming do you have any rightdates planned?

**Comment by SOF3** [comment]
Looks nice.
![image](https://user-images.githubusercontent.com/19623715/42731931-1aeb3bde-884a-11e8-95f3-004d0c73ba7f.png)

**Comment by jojoe77777** [comment]
@dktapps do you have any frontdates planned?

**Comment by dktapps** [comment]
@jojoe77777 do you have any backdates planned?

**Comment by jojoe77777** [comment]
no u
