### ISSUE TITLE
Please update to 1.5 pmmp mcpe version

### ISSUE THREAD

**Issue by CuongVnZ** [jojoe77777/Slapper#167]

**Comment by dktapps** [comment]
https://github.com/jojoe77777/Slapper/issues/166#issuecomment-405424947

**Comment by CuongVnZ** [comment]
But 1.5 still api 3.0.0 ???

**Comment by dktapps** [comment]
we don't support development builds...

**Comment by CuongVnZ** [comment]
So how long for pmmp to have stable version of mcpe 1.5?
