### ISSUE TITLE
/slapper spawn error 

### ISSUE THREAD

**Issue by SuperAdam47** [jojoe77777/Slapper#171]
![image](https://user-images.githubusercontent.com/16169771/44161413-eb363580-a0c5-11e8-8cab-b04a30ba3daa.png)

@dktapps  @jojoe77777

**Comment by SuperAdam47** [comment]
pocketmine version 3.2

**Comment by dktapps** [comment]
![image](https://user-images.githubusercontent.com/14214667/44161726-0b5df880-a0b6-11e8-92ab-e5eb59418469.png)
get out of my face
