### ISSUE TITLE
Dev PMMP SlapperEntity::saveNBT()

### ISSUE THREAD

**Issue by isoz** [jojoe77777/Slapper#174]
`Fatal error: Declaration of slapper\entities\SlapperEntity::saveNBT(): void must be compatible with pocketmine\entity\Entity::saveNBT(): pocketmine\nbt\tag\CompoundTag in phar:///home/facprimo/plugins/Slapper_dev-58.phar/src/slapper/entities/SlapperEntity.php on line 21`

**Comment by dktapps** [comment]
dev builds aren't supported, please use a PM release.

**Comment by isoz** [comment]
I think now this is relevant.

**Comment by dktapps** [comment]
nothing has changed, we still don't support dev builds since the last time you commented.
