### ISSUE TITLE
Spawn rotation error and /slapper eidit <id> rotation

### ISSUE THREAD

**Issue by nikoskon2003** [jojoe77777/Slapper#175]
When a slaper spawns, it doesnt spawn with the correct player's rotation.
Also a good feuture could be do edit the slaper roatation after it is spawned.
This could work with 2 ways, look at the player, or the player's rotation!

**Comment by HyroxPE** [comment]
Hi

**Comment by Aericio** [comment]
you can use /slapper edit (id) teleport to reposition it.

**Comment by Gianluxx** [comment]
They always look North. Now with 1.9 Pmmp they don't save the Yaw :/

**Comment by Gianluxx** [comment]
any updates?
