### ISSUE TITLE
Players can move slappers

### ISSUE THREAD

**Issue by ManiakMCPE** [jojoe77777/Slapper#176]
Please make it so when players shoot a slapper with punch it won't move them. This is a very annoying bug.

**Comment by mikemike17347** [comment]
and what the permissions

**Comment by jojoe77777** [comment]
Slappers should never be "moved", only teleported specifically
Processing motion should be easily overrideable (not a word?) in the entity classes (SlapperHuman, SlapperEntity)

**Comment by SleepSpace9** [comment]
In my case **Level::ExplodeB()** (https://github.com/pmmp/PocketMine-MP/blob/3.5/src/pocketmine/level/Explosion.php#L199) moves Slappers, no matter if EntityDamageEvent is cancelled or not. The impact is calculated regardless of the event so $entity->setMotion() will always be triggered.
My concern is that, if we cancel EntityMotionEvent we won't have a possibility to use Entity::SetMotion() on slapper entities by another plugin.

**Comment by jojoe77777** [comment]
Slappers are supposed to be stationary NPCs, if someone wants to do something else with them they can figure it out themselves

**Comment by SleepSpace9** [comment]
Ok, then the fix should be sufficient.
