### ISSUE TITLE
Mob in water well, crashes server

### ISSUE THREAD

**Issue by TheDeibo** [jojoe77777/Slapper#179]
Put villager in a village well, and it crashes the server every time a player gets too close

I can't provide a screenshot, but here is the crash log

[Fri_Oct_12-16.36.14-UTC_2018.log](https://github.com/jojoe77777/Slapper/files/2473879/Fri_Oct_12-16.36.14-UTC_2018.log)

**Comment by dktapps** [comment]
yep, this isn't compatible with 1.5/1.6 changes at the minute. I thought it had been updated, but seems not.

**Comment by dktapps** [comment]
Latest dev build on Poggit should deal with the issue. A new release will be created later once it's been checked for other changes.
