### ISSUE TITLE
Bug report after create slapper with command

### ISSUE THREAD

**Issue by dadodasyra** [jojoe77777/Slapper#182]
PocketMine-MP Crash Dump Sun Nov 4 19:48:53 CET 2018

Error: Class 'pocketmine\network\mcpe\protocol\MoveEntityPacket' not found
File: Slapper.phar/src/slapper/entities/SlapperEntity
Line: 84
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Slapper v1.4.0

Code:
[75]         parent::despawnFrom($player, $send);
[76]         $pk = new RemoveEntityPacket();
[77]         $pk->entityUniqueId = $this->tagId;
[78]         $player->dataPacket($pk);
[79]     }
[80] 
[81]     public function broadcastMovement(bool $teleport = false): void {
[82]         if($this->chunk !== null) {
[83]             parent::broadcastMovement($teleport);
[84]             $pk = new MoveEntityPacket();
[85]             $pk->entityRuntimeId = $this->tagId;
[86]             $pk->position = $this->asVector3()->add(0, static::HEIGHT + 1.62);
[87]             $pk->yaw = $pk->pitch = $pk->headYaw = 0;
[88] 
[89]             $this->level->addChunkPacket($this->chunk->getX(), $this->chunk->getZ(), $pk);
[90]         }
[91]     }
[92] }

Backtrace:
#0 src/pocketmine/entity/Entity(1137): slapper\entities\SlapperEntity->broadcastMovement(boolean )
#1 src/pocketmine/entity/Entity(1390): pocketmine\entity\Entity->updateMovement()
#2 src/pocketmine/level/Level(741): pocketmine\entity\Entity->onUpdate(integer 177)
#3 src/pocketmine/Server(2361): pocketmine\level\Level->doTick(integer 177)
#4 src/pocketmine/Server(2510): pocketmine\Server->checkTickUpdates(integer 177, double 1541357333.2215)
#5 src/pocketmine/Server(2256): pocketmine\Server->tick()
#6 src/pocketmine/Server(2134): pocketmine\Server->tickProcessor()
#7 src/pocketmine/Server(1700): pocketmine\Server->start()
#8 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gsp_2078/g3.hmserv.eu-19141/, string /home/gsp_2078/g3.hmserv.eu-19141/plugins/)
#9 /home/gsp_2078/g3.hmserv.eu-19141/PocketMine-MP.phar(1): require(string phar:///home/gsp_2078/g3.hmserv.eu-19141/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.3.0 [Protocol 291]
Git commit: 88a5e92c20bca5a0f070ec0e51d849ac86ee8212
uname -a: Linux g1 4.5.0-0.bpo.2-amd64 #1 SMP Debian 4.5.4-1~bpo8+1 (2016-05-13) x86_64
PHP Version: 7.2.9
Zend version: 3.2.0
OS : Linux, linux

Loaded plugins:
ShadowAntiCheat 3.6.5 by DarkWav for API(s) 3.0.0
WorldProtect 2.3.8 by aliuly for API(s) 3.0.0
WorldBorder 1.0.0-3.0.0 by ArceusMatt for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
ScoreHud 1.1.0 by JackMD for API(s) 3.0.0
AntiSpamPro 1.4.1 by awzaw for API(s) 3.0.0
Slapper 1.4.0 by jojoe77777 for API(s) 3.0.0
essentialsTP 1.2.1 by  for API(s) 3.0.0
PurePerms 1.4.2 by 64FF00 & ProjectInfinity for API(s) 3.0.0
BuilderTools 1.1.0-beta1 by CzechPMDevs, VixikCZ for API(s) 3.0.0
BlazinVanish 1.0.3 by iiFlamiinBlaze for API(s) 3.0.0
FactionsPro 1.3.12 by Tethered_ for API(s) 3.0.0
SimpleWarp 4.0.1 by Falkirks for API(s) 3.0.0
AdvancedKits 5.2.3 by luca28pet for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
GrabBag 2.4.3 by aliuly for API(s) 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtW31z2zaa/ypYJXO1b0VZb7ZkdZyZ1LGb7MaNL3aavV3tZCASkliTBEuQtpVO7rPf73kAUqDi
JH3J3Nwfzcx2RRB43t8J/9Ip41R1ZoPD8WB0OBmNRt1OIk15VhS66Mx+6ZSbHK879rnbSZUxckUr
p9hmxDe5Dm9UmcaZms8zVd7p4mY+T8Mcj3mhSx3qZD6/0LfqLCvjcnMpafs3ItOlWOoqiwBzWSXJ
eZwQ0Hwti9nBwcFap+pgZfJ3w/5kerAa9dapUcVtT1XB4HgwHhzkSbWKM3Nwlcg8V0WPDh6YIjww
duFAEbpYNTsseuzLCaPF9hsP42ACPjuz6bjbKQsZ4ue/Oo/6go5u5WBPbw7sob3BYDTZnwkHej6v
Yc/nLeDBk0WhZRRC9iStFNv2FlonSmZiH5gfDb6AZnTcBxpfHXbDfF4jqPJIlqqBzlCHu1ATdauS
g5f0373JePAFkDp7w0D34qxUK1WIwWTCcEe7cK+gPlXsDUdHuzAZ43zOKIMnkb6Ow5uP4I0/Be9w
sMu2fRM8CdcqvCFglkTjw+yKSFeLRImt3feGw8Eh4zr8FK7h4dEncJVEMx8++tThwWj8mcOXhQ7h
WrqwUCafgDKY9D/Frill4ZQ63T19yT8v8HNvOD7+BIB370KdmbKownLvO2kUO/hL2CREphc/qbDs
ts5VZZzAii9knL3Uq5W3C0DibCW+7MW/YWvt8Mzg8a84sOU5uLhkF98jyyvUz1VcqD2H+FcHnI/B
HXxSyBRl9jv//tDtqP/LMPpHgxrotVLeQsHbUEeKOJgcYlm4f7ksAG42i5TJ5V12Xuh073GeyI0q
uuKxUVm0/y3OTo68M4/zG3EiMnUnXqt0h5M9u33S3h48sfHmTRb/XKkXEY4/LtexgcvI1YuIj0xb
R5gCBBFZSgcYYCzsY7fxAx6mfTzQ/w/cYo5gEIdiWWVhGetMPByLgV0lKtdFCUqWMjEKBnWr40j8
QsCGHinxcs+RGq6r7Eb85QSsI8/t260jb6svz4/xNiiZi+l45+BWqBcPinR6+PGBWqyvq4yS/4Ny
nR49dC7XJmb5NAek+REur4vR3j4eomivTz4tEdJms+dnL75/fi3+Kga9o6GlZvIQ1I28I4CMIC7D
df2wVjL6b37X58NTp7TjXSCWlMQmEBBxSiKv9e9pIXiyUuU/9va74qPVf/Kqs5XjvoeB7OV44BnP
Men5Q+fDnzXAnzXAnzXAnzXAZ2uAbmelMlXIhFJoJqnV6rTAgBVI3iCo4s2oN+r1sbKo4iSipmyC
dqzO/53Z8HjQ7cg89nau4hJP06k8VMfDcNhfhPJQ9pf9SV+FfXU4iKbjYxlOj5SaDgdDHCjkTRIv
cKbfGwwZROXIehln1b1YDcS4d9jrB/3eIte9YSDT6GgsEHquLi7FM7WIEYxoxzgY/A92TP86EHvD
/uAo6B8Gg9G+uJ8evTsaAy61WrPOpDfsHePpPWoCptsixct32tRYscAPCT80dYghoV2tZaTvniLY
nCIhlJ4cd9+0JXnUO8SKrMq1LgwF6WeyuHkrb0knLMN/YVMfxOBZZRKBAPTB8lW3E6kc1NIhvDN6
WT7zF1LJFZIDB995esr/oUoKnkKEXT99ff2GVHunFsiYRCxx9VYXSQQvL+EhHh+tZZ+JIZQ8bTMh
k7hKNl+LBwttPr8jCnJLgfXmzzOzLsvcwGVgfetq0Qt1enABj1rGKok8dwhqhy0LpQ5SpDWUoS1u
a6F8pwuEmF2ZuFVfJANiN7BMtwTztAhVZS5kWX4t4Xgk7Mrk8tXV9dtXr18++5JUJFOVElVg9QzB
Vaebp5cvPE69RZ/Rwx48p82iztQC//ta/DlwSOiWAsBEUvep+Sy3xNBVqAv1vIp8p6yX2lob7Orr
byjPLp59LV4sNLihw/7rFEYsUPi4ymUKi/S48FfbjIx7gx2PvHsv7z7LB3cKv9YjCdp8LoEfnVUK
n5zP28R8WSmudfN00jRzbU52VPKT/kmrCf37WmppCt7f6T5biuqmlRhEjUQ1KKR6felx2Vpuszrc
UdpXYs/HCDdq4/+ini6rQl2qIjV+adCs7epqJxYcjc/P+33xHwJGQQXXi2wZZ9TOfyXW3lkE83lD
kffzd2iSz7pssIUDKXxHpY4qrtHm+IJoLX8USoKFKuWOH56+V+H68uKZuqUDP8b38c3pP7+WOEIC
nqcRgM/nC0tbSbTN5zuU/lbBeGQftECRbBL5Ps5+lFls1r5s/OXd5DhqSyWOzxOZxnFGh75a6mhD
hQw8itpPv8YRziUPXUw7BPurbSZHvcGON1yrcq0KFb37Ywyy+52uuZT0g+6WcY+o+dw9/NpMcxWn
eaLeyiL3Q/N20WcSsXk3z5zL5CYubswfZPEcVdh1ITOz5IRwleg77/GsiWGXZx7bS4d7PjdM7x3o
RbL1af9yoo1uZRaq6O9x6Tt6a7ldAA13jTmpQjmc5qr8CmquA9llvFptTitT6vQsC9dIvLR6rouU
aqCtCHw6f3c+axg4aLHtkgFbXjsXOGPcKUAGD+WC3yQTTwQPmYjvef9Qt7GuYA9Bvd75RJogYre/
vkKSYDAQzveFXHwnV55s6pV2tzTeNZiv0S21Pebj3mkFUhZy9bttYts41Ux9oAZYFuAU/RKT0Htg
9AC4c6bH8Oymh1IR9RFNFYHn0WXzJE41aoOVoM8D82KePbqqMvGDvhVjMTiejaez8Uicnl0L9PBT
ep/qMjqZV/2+nITfxSq7VVmlhKkKcWbKOIml+HEo/kI7LeKAhtMnPCDh4yrVxSZI4jTGan84vqDV
uzX4x6IpT/RySSsyy3QFDwjczF6G61jZqaQ50RnDp08LgWtLoeOTISyNUMh7d8qcHPKKTBDGgmUS
r9Zl6zByUIpg1lpL9cLUVKwk0RupEwaz1GjXgmbN7YGsI2or6uf8Nnfwoni5jMMqKTcnQ4bGo55S
F4FRZRlnK3NCy3YwTZZ7wo32ds0oFXlb6CPRybOz86dvXl7TqjXS4OdKFRuH0i0VaNNqeuh3L5fG
AHh08p/8DyKpSh0Yeatq3q2y4vzEH2zRG53RB6DAZ/k2VndBBG1RjDphs7hf6PuAXMvBoxlO0+j3
NmlCVifIB0TIBldBEvSpgOxOQLKiZcKwQ3G9VgaW5UQlZKEE0rhAT2rwQ5YiJCMpxUKJOAuTKlIR
foiP7J1gXekUJ5cEYBemkUvVFZoqBEMgxaJQ8kZsNEzawhLxUoD9GG5IGKDsAhYH5wbgH9RdA+4g
UksJdRtxp7NvSkEdiSwEiTqlTx4www1RSB8XLN93a5WJKkeMiACgN89IERbYbJ6JR9frQsEvsAQq
EpmtKrlSgj65scic0kyM50QDfvyehUpHT2m0bbloH4TM6zCjst5dfBPnKoplTxerA3o6eAnFvtPL
dy+uXr07Gh0Hw3d0DmJsAM3EHBFyNe8Qordrrq5EqQV92BPg0o1soSaKi4ksITd+zdJkSkEHfqmS
VYq6OQ6VQHaNElZyCsDW27YouU3GullXZaTJUe1HUiLGzqdFmGijIkvWU/J5QSGFZ7g2bYhbxKf/
In/BFvabegY1ExTp6eDVGuckWanRoMZhsaqSDpCoDIwQWQGGwNyhGMBOJJaI5LR9EYCsBYjagj9j
D63hgGNBwUPAXGERROpiI5wdYbvz5+btVgyP3sYQNJxzI2QUiUIZa3lEJn0tADkSUZkjpoC9LRTJ
A0JXP1cyIXWsYsRucSsTxO89hxJhfh/ALT7EEf60GECbNLyf4S1h/qFKFzTKX4qnZpOF19LcCPoi
DQfq0fs3UALbZ80k7VoXGhEdJoHdpis40gkXEWGyXYghhdQMZWsWC7IiraVVBs+hLQz7ik0G/MC5
Cn2P8F0qiADssKlnDWkkVUvOiyV5KG0hT+yKuPwGkisLPhUpyh5shTtnxR44gJ7FkCTCPASOyxlD
2jF+TjKiqLKMtBhRxNY5S58bQtMTaOLcb5FSKhJhIc266wccZ40kjaKo8tKuWmGRUJA8lWWKlQor
g4TgddbBJH9srszDBJBtkKVpyBhG1duaF/YGdk9jX3Wm5jD0faIXsBkqfIRdFpzAKZilaiUXmxKy
FldWyn2Wa2wItA1ioPQuZpmzHQnKxq4QcEuGuVvGoA8RGKRnDGqJ8FdjtJYNPVXsjysNFWnyejIH
4FkxkbaymIn+nKMgJ5wSUVRG/8/Jp7LxM8RTlfGHiEcHkzN+F4Ubehw0QzUclQkIoI4awlmTRKWa
pYp9/i07giPOfPPHyWNXYHooQIiwKujGAzxb3auw4hiuLb3WByknN7vVfYhKyWzZ4Sj16vpsJq6f
v7gSL19cvLhGjL58+eLsSlyevRYovf9+9rorsElcv8KuM/H2+auXZ+Ly9avTs6ur3o7Lt2QxPDyy
okCHFGsuOijiGmKOvyjXkmii6gBSR0KJKJLwjgBRT9l4yslao6umOhomRKx+ysKsZaFaTjiPU8Cx
2+ZcVhEMxNhtvLZJhzC8okRBdQxv7328mSzAdT1QV65CKnesSIlWq097tmEARqVys2Vz1Hd8mv0H
CXJcjyzXK1mgMVJBqJPEVvAUbB6UKnsWkeLOCHcGETqVWcWFlU8Fis4KdrffrSP/juE5y7PZc7kE
JMtpuvW4nnhlI7s1cZQdukqihpIYieIuE1vayYdFzqSDw6N+3zIpHp1zVPgoBbKx2NMNV8tCp3Um
pbPufeBboqdUcOF0t2sLDxiQbwxXdf1LKiqAhGzO2WxUpbmtxGxF6tYDWrf6eUY73G6mmMmr6cYT
Ujc8Wj4gUqRiJDSAv4VBGVMp8v5yDS2t6sqZwhLh2pLUrRVnE78rkIk03vgp6VAbyBd4jCX7VOa0
FqdViryZ0ZWFuoUhvQnbMloCtsIkt3ASZMf42JzQM+RMjL0tRKV8hTw6dip6pu2LXdOlMocimoVN
W2snsXDcNo8hrgKCEJ2wciw9AwVcdaACJHmBKFsqWBA5X3ES9oRlbMsUjrEELRM1Utra1KqQWUIN
jIP5OTCfs7d55m4sNi0NfCmxFeJClmjsqUBnWlH4wFpczuCQZRs299amioVqakXOVY98pdRvKFQW
m5Jgd0Uw8PRFumK0QVmT4kI6xeFtDco9NxWAkeWZmhuuz+ksFh1NPfEctRwM54SLM3F6+aaLs6Bg
ASe6iyOYN6d8jogN+IDBz8TEFczbUtqwYLytPfE0QgBay2R5gObXVveRgrk6REApaKxE9uS5W5PC
PFhe/3B2T9GK6kOZdG0oJMRv4wzdFdhCbFEcpagGfnOZXdYV9LaX5auOOHSH5DinRjbLA/fY7lUu
nN+Z+L1qNEyVdq1YGivX5RAqcWsvXv4cHw/tof2euHRnElms+IB0LbWzDkK4LOSKWIOeqE/OE65I
qAdNQTl5uyxId6dJTBMl7vvp2o8ypbi4fsOEGjBEPC+qki/Ssnq32Gy70HORJi2rgA7NmFYy+kgt
qpU1ee0yq6DyqmDXd2UNNT6Uouj6S695a0hGth9Y5704i4mMAeuz3mEDwFtZZJTVvZM00nB5nKA4
AIihqC5IgdudqYQHp9BASYZT2NueFAqhwpTDIiDXJQGhg16zIF4Gbm3b0yKsPxED6qxcrUktNPNf
t8/Gzj1U3VbPnX/NmC3XFBtxQHdDK0SBg1Vo/QWEtLoSG6VndsKh0VmTc9YtmKp7a47kdMtXGHnr
kgUNu+ppIr1qyKeP6Yh/SpZWqODGfpKvq35uFOFBXHyZHKUmF2OZDpM4F3wSpnQBcYaSnCV11ydd
imPZ2RFk/caiM9sYWc/7WrMfVQ8CBGuktFMv3uqMvTJuMBHC4UuOhu5IYI/MRA4J3sYJV+4t56WP
GUhHDhwHFa7pwCsFkZICybDvajBKkLa0I4HR7JDWXT1Xy7G13BTLfReibTmwkEZ5yPYGiJsPYOmK
IV4MHnqhyrC3zzHcKJ8KNiS6y8kTKDcAFgpZy+Ij9Vlh8axvOwSM6ixKbs2Ff3InN8bCdnA8C7SZ
0mWD2r+dMF1vlZHsk90qo1vvao1PHxxZcov/NNUVRcWlTecuSJIpOt5IKkQkDWxg1PST6w7x6DUX
Id5RtpxM2THBQllQC7WkkMZjby4f1rXvkLvwMLxVzVjOCU3NOeK6kLtk5vaeKnA1wm9T2H+QRFnQ
HyrwiI3dF4S6o07JlpIRhQ6angT2rvJWNSKkasWqjeZ+Xnx6xogWiSZjolhOUrSBDnaIhJcKx5aw
c6a6LOIjPsviUQDTfCRW6FfNVijbQVYtl97HgnEh8E7G3M8i29iYvKChTF4lzoPdbyoSeIvLK1PC
xu4Q5DYCksNRVJuJut1gF7RDu5l1O5ovcmttV21x4TQEIpoZ0Daak2UHNPFtrzSxqbWK9BJnS73V
ASJSYMfL9b61JlUwEb08TZGONJOa6WyTUnPIfw9gwJlpaKZu170W29dMO0d1uVoVauUGh81Ilqpr
unN/s8MY0wY3ffXsFV3udfnL1QwUEO6UbUkk/6UEITRMdkM9L/W8DxqoUBp5WztkjezKEiq0b2dN
/nQJcFtk86r2BIZOJSOb8CZ4XcSkfC27gi62cEVT1qUs8tJSFWhOAoouGaVU+9IlZjsNlK15oPso
6iXsCiU7Sh8OUHUocPBI1fZ1jWFXt5ZFX7moJJo85tI0QaTtdUVJuqRASNi41HFn6kl2rwHvXvjw
ayF+tgxwwdiq05q/N0aq5/tlXFpB1gOjtVvjiEANoes5XEigUTtauYgr73jZwEG/Bi5s/UURxiuc
GJwLfk0akUmMBGZFdHYv6aqEfaDiCQQ6Hc1qZfErGCnN8WbiX1zNIG11ebD3b4LIbVpTO/ifuZgF
qq4L+lLEc5T6UyRXnw+lIC5xOC8abi64H4diYhDqigaPdMbKBPAvQV8uKdJzNtpim4nzl0+vZ8Nv
J93D4/tBd3Q/6g6/HXwbIbfb8LlHd4FDCpwn076NsvZpfLhv6z/7ucYbY1hHpnQBo3TTRK7DeBwI
ZYUbYf9moSrqeFu3dUXzJYbjCuAg+4RcOptaVkH9jQgmwPX+o3MOKIyJt7dgVJz07co7byXgqrPX
jD117hoBBDfjmuHwhnonw90fxLGI0bds7IiE9xG3IAQdm00Q7CWWRYaOqqJobKzT7aj7UmWGL2XM
fumcItt7V+7Jab1HKD4zJvFW8rC13/wMatTIv7Rv/1SgflyEqC7X3gJ958siWfhLxSYvNf99wYiv
MIXuTx+bDVXh0/CTcfdajvg66jJOSuXDW5b+XxGsIv8h9V+tJV2S69iLxlR6gS5/99XlS+8pXdhP
mP7SBgLgP1Jwv8Qh3cIa0tcTEdD9iMP+uD/Bz8cvaAQ4XSo5HC+H0/FkKSeHg+N+f7BQo+N+eDyV
qi9DuVSj6UQ8Zklnpc/15ZqFNgSCIX9JN/G9rxg3lOQ/ZBj0JqAAq6/V0g2WfKWtU+2LwXAOM74Z
GHcH9ggP8WoRZ7LYOOQTLJX6RmWoQHypbyR/0K/pex/n9urlId+wYfnEzfYPH/4XTC7jrA==
===END CRASH DUMP===

**Comment by dktapps** [comment]
Already fixed, just pending Poggit release. Use dev build 59 for now.
