### ISSUE TITLE
Sometimes npc can't use it

### ISSUE THREAD

**Issue by junxiesky** [jojoe77777/Slapper#207]
PocketMine-MP ver:3.9.4
slapper ver: 1.5.0
MinecraftBE ver: 1.12
Question:
Sometimes, when I turn on the server 
NPC didn't respond to the click
No logs
need restart servet To be useful

**Comment by LukilukinoSKCZ** [comment]
It happens to me too. Every time I write /reload commands, they stop working. Therefore, I always have to restart the server after editing the plugin. /reload is not great option. Sorry for my bad english. I am Slovak :/

**Comment by Johnsonk79** [comment]
Same goes to me, it just randomly stops working, but from my observation, it happens because the world that slappers are in are not loaded when the server is reloading/restarting
