### ISSUE TITLE
Game Crashes when I spawn an entity such as a mob... Can you fix it?

### ISSUE THREAD

**Issue by gavb123** [jojoe77777/Slapper#211]
Minecraft PE Crashes when I spawn an entity such as a mob... Can you fix it? It lets me spawn a Player like a human and game does not crash but when I spawn a mob game crashes. Please reply with support.

**Comment by Gianluxx** [comment]
What version are you using?

**Comment by gavb123** [comment]
why does the version effect it?

**Comment by gavb123** [comment]
Oh and I want to compile a Pocketmine-MP server phar I made but I use a website called minehub and Im not running from src code is there any way other way to compile a server phar to Pocketmine-MP phar without devtools?

**Comment by gavb123** [comment]
I am not an expert on pocketmine...

**Comment by gavb123** [comment]
i cant use makeserver because im not running from source code.

**Comment by SOF3** [comment]
This is an issue tracker for Slapper, not a support channel. Please stop.

**Comment by gavb123** [comment]
ok where do I get support?

**Comment by Gianluxx** [comment]
1) answer a question when asked, even if it's useless and requires 1 second to reply.
2) modifying source code can break plugins, so tell me if you are using official pmmp and version
