### ISSUE TITLE
1.13 Support

### ISSUE THREAD

**Issue by Tcode209** [jojoe77777/Slapper#212]
# 1.13 shall support Slapper plugin!

Minecraft Bedrock Edition 1.13.0 officaly relaesed and some server support other Slapper plugin right now like **[Hive](https://minecraftpocket-servers.com/server/89911/)**.

I need to play my favorite prison server, i cant sell faster by clicking it quickly.

**Comment by provsnoobgaming** [comment]
Slapper follows official pocketmine.They don't follow 🍴and 🥄s

**Comment by Tcode209** [comment]
Ok i accepted...
