### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by supercrafti** [jojoe77777/Slapper#214]
Hello, could you please plugin on the Pocketmine v1.13 Reprogram? The plugin does not work anymore in 1.13.

Hallo, könntest du bitte das Pocketmine v1.13 Reprogram aufstecken? Das Plugin funktioniert in 1.13 nicht mehr.

**Comment by LeronHinds** [comment]
Slapper only supports the official Pocketmine releases. Forks and Spoons will not be supported.

**Comment by supercrafti** [comment]
Okay, so you have to go to the new version of Pocketmine Waiting.

**Comment by provsnoobgaming** [comment]
Yes you will need to wait for pocketmine to update to 1.13.No `[Read this](https://github.com/jojoe77777/Slapper/blob/master/README.md#note) `
