### ISSUE TITLE
Permission problem 

### ISSUE THREAD

**Issue by Tolo0** [jojoe77777/Slapper#22]
Not sure why but when i use this plugin i can't log in to the server. i get the no permission to log in  msg. Slapper seems to be effecting pureperms or simpleauth

**Comment by jojoe77777** [comment]
Can't reproduce

**Comment by Tolo0** [comment]
Sorry about that. i forgot to add - simpleauth.command.login to a group. 
Instead of opening a new issue could you tell me how i can remove or hide the Entity ID ?
i tried doing /slapper edit 3 name random
but after reboot the entity id is back.
![screenshot_20170211-151319](https://cloud.githubusercontent.com/assets/13458191/22854832/888629d6-f06d-11e6-8bde-e2a627be07d9.png)
![screenshot_20170211-151319](https://cloud.githubusercontent.com/assets/13458191/22854836/93035122-f06d-11e6-97fc-41d1d44b66da.png)

**Comment by Sandertv** [comment]
The entity ID is only visible to players with the permission.

**Comment by Tolo0** [comment]
lol i feel like a big noob. i spent ages trying to figure that out. thanks 😉

**Comment by Tolo0** [comment]
hey not sure if im doing it right but i cant get it to work. im trying to add armor to a slapper. im doing. 
/slapper edit 4 Helmet 310
and 
/slapper edit 4 310
i just get Unknown Command... am i doing it wrong?

**Comment by Tolo0** [comment]
How do you add a weapon to a slapper?
