### ISSUE TITLE
NBT Tag Issue

### ISSUE THREAD

**Issue by ManiakMCPE** [jojoe77777/Slapper#221]
NPC's disappear when updating PMMP version

CONSOLE LOG:
https://pastebin.com/bbL1fpiF

**Comment by dktapps** [comment]
> This plugin is designed for PocketMine-MP only and we do not support any other variations, forks or spoons. Compatibility with unofficial variants can occasionally be found, but do not expect support if you are using anything other than PocketMine-MP.
