### ISSUE TITLE
Slapper sometimes not working

### ISSUE THREAD

**Issue by BlueWhaleYT** [jojoe77777/Slapper#229]
Hi there,
Slapper is a amazing plugin for creating NPC and add commands to NPC.
But,when I restart / reload the server.It sometimes doesn't working, especially when added command to it.I definitely judge that it doesn't work.

I don't know is this happen to me only.

Thanks.

**Comment by Johnsonk79** [comment]
Same for me

**Comment by ZZWILLIAMXXTrue** [comment]
Same

**Comment by JJBirdmanYT** [comment]
Same
