### ISSUE TITLE
REQUEST-MultiWord_HitEntityArrow_Support

### ISSUE THREAD

**Issue by Starflux** [jojoe77777/Slapper#23]
PHP 7.0.15
PocketMine-MP-1.6.2dev "Unleashed" (API 3.0.0-ALPHA3)

Slapper v1.3.3
SlapperCache v1.0.1

1. created a slapper in my default **world** /slapper create villager bob
2. /slapper edit *ID* addcommand item 19 1

now when i hit it with a sword or fire an arrow from a distance it registers the hit entity and drops the item.

this is great as i would like to use it in a game for my kids.

however, when i create a slapper in another world i.e targets only the sword hit registers and the arrows fired from a distance do not.

No errors are reported in console.

is this something you would be interested in looking into?

Kind regards
Star

**Comment by jojoe77777** [comment]
Arrows are not supposed to trigger the command

**Comment by Starflux** [comment]
ok thankyou, is it something that you would be able to implement?

just it really is a nice feature that i would love to be able to do on worlds other than the default.

**Comment by Starflux** [comment]
Workable using Human Entity.
