### ISSUE TITLE
Cant see slappers on latest pocketmine version

### ISSUE THREAD

**Issue by AGTHARN** [jojoe77777/Slapper#238]
Im not able to see slappers in the latest pocketmine version. Does it have to do with the mcpe protocol veesion?

**Comment by Taylarity** [comment]
Create a fork and add protocol 390

**Comment by IR0NIIC** [comment]
How do you make a fork

**Comment by AGTHARN** [comment]
Yep, I did that.

**Comment by IR0NIIC** [comment]
How can i update slapper?

**Comment by AGTHARN** [comment]
Take the source code and add 190 to mcpe-protocol in plugin.yml.

**Comment by IR0NIIC** [comment]
I did that bit nothing shows?

**Comment by Taylarity** [comment]
It's protocol 390 not 190 😂

**Comment by AGTHARN** [comment]
Yeah i know xD i just didnt know how to edit the comment
