### ISSUE TITLE
Slapper chunk error

### ISSUE THREAD

**Issue by xBeastMode** [jojoe77777/Slapper#24]
Error occurrs when a player logs into the game.

The error produced: 
`Error: Argument 1 passed to slapper\entities\SlapperEntity::__construct() must be an instance of pocketmine\level\format\FullChunk, instance of pocketmine\level\format\generic\GenericChunk given, called in phar:///home/server/PocketMine-MP.phar/src/pocketmine/entity/Entity.php on line 625`

PocketMine API: 3.0.0
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

**Comment by jojoe77777** [comment]
Update Slapper
