### ISSUE TITLE
Not supporting Elywing and Tesseract

### ISSUE THREAD

**Issue by ChickenTheDuck** [jojoe77777/Slapper#29]
Please update Slapper! It's currently not supporting Elywing and Tesseract

**Comment by Sandertv** [comment]
Would you please look at the README?

**Comment by jojoe77777** [comment]
You are correct, it's not supporting Elyeing or Tesseract.

**Comment by ChickenTheDuck** [comment]
Jojoe are you gonna update it?

**Comment by Sandertv** [comment]
I zoomed in for you. Here:
![screenshot_2017-02-18-12-04-04](https://cloud.githubusercontent.com/assets/16114089/23092661/8d5d3fe0-f5d0-11e6-99b3-dd6ef6d00cf0.png)

**Comment by ChickenTheDuck** [comment]
Will you support them?!

**Comment by dktapps** [comment]
If you search the issue tracker, you'll find that question has been answered several times already.

**Comment by HimbeersaftLP** [comment]
![](https://media2.giphy.com/media/hXolrwC7WwX7y/giphy.gif)
