### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SinlesFlyer376** [jojoe77777/Slapper#33]
Whenever I do /slapper spawn Human (ex. Hello Human)

It just says there was an error or something like that in light red how do I fix?

**Comment by Sandertv** [comment]
Please show the error given in console. Without it there's not much the developers can do about it.

**Comment by jojoe77777** [comment]
I bet 50 likes on the pmmp forums the error is because of Elywing, or outdated version.

**Comment by MorpheusTP** [comment]
Getting same error using official PocketMine_MP.
Console messgae:
![screenshot 1](https://cloud.githubusercontent.com/assets/22548878/23415179/b098059c-fdde-11e6-8c15-136baacfa530.png)

**Comment by dktapps** [comment]
Your PocketMine-MP version is outdated. The current master verison of Slapper is intended for PocketMine-MP API 3.0.0-ALPHA4.

**Comment by Sandertv** [comment]
Jackpot @jojoe77777
