### ISSUE TITLE
Slapper dont generate a config folder?

### ISSUE THREAD

**Issue by RocoWayne** [jojoe77777/Slapper#34]
Slapper works without a config file en /plugins?

**Comment by Sandertv** [comment]
Slapper does not generate a config file no. It should show up at /plugins like all plugins though.

**Comment by RocoWayne** [comment]
so where it saves the npc data? In the level.dats?

**Comment by Sandertv** [comment]
The NPC data is stored in the NBT of the entities.

**Comment by RocoWayne** [comment]
but if i remove slapper the entities disspear, the entities are in the data of the map?

**Comment by Sandertv** [comment]
The entities are stored as normal entities in PocketMine would be saved, so yes, that's how you could say it.

**Comment by RocoWayne** [comment]
but if i remove slapher.phar the NPCs dissapear... so, the plugin must do something to make that entities work, i mean, the entities are stored in ....?

**Comment by Sandertv** [comment]
Again, the entities are stored the normal way. Slapper registers new entities instead of existing mobs, which it only does onEnable. If slapper is not added, the entities won't be registered, making them non-existing which results in the entities getting removed.
