### ISSUE TITLE
Won't Spawn Entity

### ISSUE THREAD

**Issue by MSG100TC** [jojoe77777/Slapper#36]
Hi, I've got a problem here:

Elywing thread:CRITICAL > Unhandled exception executing command 'slapper spawn human' in slapper: Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\format\Chunk, instance of pocketmine\level\Level given, called in phar://C:/Users/PC/Desktop/PocketMine-MP/plugins/Slapper.phar/src/slapper/Main.php on line 619
09:40:35 | Elywing thread:CRITICAL > TypeError: "Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\format\Chunk, instance of pocketmine\level\Level given, called in phar://C:/Users/PC/Desktop/PocketMine-MP/plugins/Slapper.phar/src/slapper/Main.php on line 619" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 613 

How do I fix that error?

**Comment by dktapps** [comment]
By not using Elywing. I invite you to read the [README.md](https://github.com/jojoe77777/Slapper/blob/master/README.md).

**Comment by MSG100TC** [comment]
What would you recommend me to use tho? I can't seem to find the version of 1.0.3 for PocketMine...

**Comment by jojoe77777** [comment]
https://forums.pmmp.io

More specifically, https://pmmp.io/get.html
