### ISSUE TITLE
2 Questions:

### ISSUE THREAD

**Issue by TheRoyalBlock** [jojoe77777/Slapper#37]
1. Is Tesseract supported?
2. Is MCPE1.0.4 supported?

**Comment by jojoe77777** [comment]
Tesseract, no. MCPE 1.0.4, untested.

**Comment by TheRoyalBlock** [comment]
Okay, thansk for replying so fast

**Comment by TheRoyalBlock** [comment]
No Tesseract support at all, or just not much?

**Comment by jojoe77777** [comment]
I'm not deliberately un supporting any server software, but Tesseract and Elywing have made changes to he core that causes errors with some plugins.

**Comment by TheRoyalBlock** [comment]
Ah, okay, thanks for telling!

**Comment by poustmal** [comment]
TheRoyalBlock,try to use the source version of plugin,for me,plugin is working now

**Comment by TheRoyalBlock** [comment]
@poustmal okay, I'll give it a shot!
