### ISSUE TITLE
Commands Don't Work

### ISSUE THREAD

**Issue by NFGamerMC** [jojoe77777/Slapper#38]
I am using PMMP and when I try to set a command such as tp for a slapped it says [Slapper] Unknown Command

**Comment by Sandertv** [comment]
What is the exact command you're using?

**Comment by RocoWayne** [comment]
are you an OP in the server @NFGamerMC ?

**Comment by NFGamerMC** [comment]
Yes, I am using the latest PHAR

**Comment by jojoe77777** [comment]
Whatever you're doing, you're using the wrong command. TP is /slapper edit <id> tp

**Comment by CyanCreeper** [comment]
No he isnt. That's my problem! An unknown error has occured while performing this command!

**Comment by jojoe77777** [comment]
@CyanCreeper there's a difference between "An unknown error has occurred" and "Unknown command"

**Comment by CyanCreeper** [comment]
Sorry, if I sounded a bit rude. It says an Unknown error has occurred while performing this command.

**Comment by CyanCreeper** [comment]
@jojoe77777 Would you mind sending me the updated version through my email cyancreeper31@gmail.com please.
