### ISSUE TITLE
Slapper not spawning

### ISSUE THREAD

**Issue by BroadSkate** [jojoe77777/Slapper#43]
Server thread/CRITICAL Unhandled exception executing command 'slapper create villager' in slapper: Class pocketmine\network\protocol\AddEntityPacket not found

**Comment by dktapps** [comment]
Incompatible version, Slapper doesn't support API 3.0.0-ALPHA5 yet.

**Comment by BroadSkate** [comment]
when will it? (if you know?)

**Comment by Sandertv** [comment]
Most likely when the 1.0.5 branch is more stable and (maybe) merged with the master branch.

**Comment by BroadSkate** [comment]
ok thanks

**Comment by jojoe77777** [comment]
Soon™

**Comment by jojoe77777** [comment]
https://github.com/jojoe77777/Slapper/tree/ALPHA5
