### ISSUE TITLE
Enitity ID under Nametag

### ISSUE THREAD

**Issue by PluginBOXone** [jojoe77777/Slapper#44]
When i spawn a slapper it shows the Entity ID under the Nametag of the Slapper

**Comment by PluginBOXone** [comment]
Why? Can you say me how to fix this?

**Comment by Sandertv** [comment]
This is intended. It's only visible to players with the required permissions, which is usually only OP.

**Comment by jojoe77777** [comment]
@Sandertv Actually it's set to false
