### ISSUE TITLE
Spawning NPC's

### ISSUE THREAD

**Issue by NeagDolph** [jojoe77777/Slapper#47]
When I try to spawn an NPC with '/slapper spawn player NeagDolph' it says an unknown internal error occurred. https://pastebin.com/qJWxRHg4 here is the console output. My server version is tesseract 1.0.6 and here are all my plugins Afk v0.3, AccidentCaps v0.0.1, PocketMoney v4.0.1, MoreCommands v1.1.4, BuycraftPM v0.1, PocketVote v1.2.0, SkyBlock v1.5.6, PurePerms v1.3.7, SimpleAuth v1.8.1, SimpleAuthHelper v2.0.5, AlwaysSpawn v2.2.2, Slapper v1.3.0, PureChat v1.4.0

**Comment by jojoe77777** [comment]
> [Tesseract]
