### ISSUE TITLE
API 3.0.0-ALPHA5 Compatibility 

### ISSUE THREAD

**Issue by Starflux** [jojoe77777/Slapper#48]
PocketMine-MP version 1.6.2dev "Unleashed" (API 3.0.0-ALPHA5)

Error: Class pocketmine\network\protocol\AddPlayerPacket not found
File: /src/spl/BaseClassLoader
Line: 144
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN

Code:

Backtrace:
#0 (): BaseClassLoader->loadClass(string pocketmine\network\protocol\AddPlayerPacket)
#1 /Slapper-master/src/slapper/entities/SlapperHuman(65): spl_autoload_call(string pocketmine\network\protocol\AddPlayerPacket)
#2 /src/pocketmine/Player(928): slapper\entities\SlapperHuman->spawnTo(pocketmine\Player Player(110))
#3 /src/pocketmine/Player(871): pocketmine\Player->doFirstSpawn(boolean)
#4 /src/pocketmine/Player(1733): pocketmine\Player->sendNextChunk(boolean)
#5 /src/pocketmine/Server(2379): pocketmine\Player->checkNetwork(boolean)
#6 /src/pocketmine/Server(2138): pocketmine\Server->tick(boolean)
#7 /src/pocketmine/Server(2021): pocketmine\Server->tickProcessor(boolean)
#8 /src/pocketmine/Server(1642): pocketmine\Server->start(boolean)
#9 /src/pocketmine/PocketMine(492): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///opt/PocketMine-MP-master/PocketMine-MP.phar/, string /opt/PocketMine-MP-master/, string /opt/PocketMine-MP-master/plugins/)
#10 (1): require_once(string phar:///opt/PocketMine-MP-master/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6.2dev #0 [Protocol 107; API 3.0.0-ALPHA5]

**Comment by jojoe77777** [comment]
https://github.com/jojoe77777/Slapper/tree/ALPHA5
