### ISSUE TITLE
Support for PMMP's Pocketmine. (The one you have linked as the only supported one... isn't supported.)

### ISSUE THREAD

**Issue by JUSTaMod** [jojoe77777/Slapper#49]
Since I really have no clue how to make a PR--- someone fix this-

Change every- "pocketmine\network\protocol\AddEntityPacket"
too- "pocketmine/network/mcpe/protocol/AddPlayerPacket.php"

And every "pocketmine\network\protocol\AddPlayerPacket"
too- "pocketmine/network/mcpe/protocol/AddPlayerPacket.php"

And every- "pocketmine\network\protocol\MovePlayerPacket"
too- "pocketmine/network/mcpe/protocol/MovePlayerPacket.php" 
#48

**Comment by jojoe77777** [comment]
https://github.com/jojoe77777/Slapper/tree/ALPHA5
