### ISSUE TITLE
Mobs aren't moving

### ISSUE THREAD

**Issue by tjespe** [jojoe77777/Slapper#5]
I am able to spawn mobs, but none of them move. The chicken is the only one that doesn't stand completely still, it actually flaps it's wings. However none of the mobs move in any direction. I'm using the newest version of Slapper, the newest version of Pocketmine and the newest version of MCPE.

Ps. is it possible to make mobs spawn automatically?

**Comment by Sandertv** [comment]
Slapper is not a mob AI plugin. Slapper allows you to add entities that execute commands when tapping them.

**Comment by tjespe** [comment]
Alright, I'm sorry. Do you know about any plugins that can make them move?
