### ISSUE TITLE
[Feature] A config file for slappers

### ISSUE THREAD

**Issue by RocoWayne** [jojoe77777/Slapper#52]
I think that slapper needs asap a config file. So, if for any reason the slapper.phar dont start we can restore the npc configs without lose it all! Also, we will be able to change from file commands or texts without enter the server.

**Comment by Lazerplayz** [comment]
<3 I love this idea, this is also very good ofr people that don't understand how slapper works like adding a command to a NPC! 👍

**Comment by RocoWayne** [comment]
why do you close it @jojoe77777 ?

**Comment by HimbeersaftLP** [comment]
The Slapper commands/skin/etc are all stored directly in the entity
