### ISSUE TITLE
Unhandled exception executing command 'slapper spawn human test' in slapper: Argument 1 passed to pocketmine\utils\Binary::writeLFloat() must be of the type float, null given

### ISSUE THREAD

**Issue by ChaostixZix** [jojoe77777/Slapper#57]
Why Everytime I Used Slapper Spawn
I Got This Error

> Unhandled exception executing command 'slapper spawn human test' in slapper: Argument 1 passed to pocketmine\utils\Binary::writeLFloat() must be of the type float, null given

**Comment by jojoe77777** [comment]
Fixed, please update.

**Comment by ChaostixZix** [comment]
@jojoe77777 Wow, So argument 1 used to be default?

**Comment by ChaostixZix** [comment]
@jojoe77777 Wrong API, 3.0.0-ALPHA5 not 3.0.0ALPHA6
