### ISSUE TITLE
Spawn entity goes down in the block by 1 and a half block

### ISSUE THREAD

**Issue by BrianZP** [jojoe77777/Slapper#58]
Whenever you spawn a human Slapper it appears in the ground until you relog

Here is a screenshot.
http://i67.tinypic.com/9ftbmh.png

**Comment by jojoe77777** [comment]
Can anyone else reproduce?

**Comment by thebigsmileXD** [comment]
-> eye height offset, 1.62

**Comment by BrianZP** [comment]
Yay. Thank you!!
