### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by infinity-pe** [jojoe77777/Slapper#63]
My server is crashing every 10 minutes and I'm getting this crashdump error:

`Error: Value 237 is too large!`
`File: /src/pocketmine/nbt/tag/ByteTag`

The whole crashdump is:
https://ghostbin.com/paste/dbhs7

I'm using PocketMine-MP 1.6.2dev [ Unleashed ], 3.0.0-ALPHA5, Minecraft: PE v1.1.0.55

I hope you can fix this soon!

**Comment by infinity-pe** [comment]
I'm also getting the "xxxxxxxx tag is too large!" error in console when creating a slapper.

**Comment by infinity-pe** [comment]
Is this a Slapper problem or not? I want to know why you closed this.

**Comment by jojoe77777** [comment]
Can't reproduce, assuming not Slapper issue
