### ISSUE TITLE
error on tap

### ISSUE THREAD

**Issue by optimusprime338** [jojoe77777/Slapper#65]
when ever a player taps the slapper it gives this error on console":-
Server thread/CRITICAL Error: "Call to a member function sendContents() on null" (EXCEPTION) in "src/pocketmine/Player" at line 2419

**Comment by TheRoyalBlock** [comment]
Which branch are you using?

**Comment by optimusprime338** [comment]
PMMP

**Comment by TheRoyalBlock** [comment]
BRANCH
