### ISSUE TITLE
slapper.edit / slapper permission does not work

### ISSUE THREAD

**Issue by thebigsmileXD** [jojoe77777/Slapper#66]
I am running plenty of plugins. Only in slapper the permissions do not work. ppreload and restart already done. Might be an issue what the perms are no subperms? https://github.com/jojoe77777/Slapper/blob/master/plugin.yml#L33

https://github.com/jojoe77777/Slapper/blob/master/src/slapper/Main.php#L263

**Comment by CyanCreeperPlayz** [comment]
Is this still not fixed yet?
