### ISSUE TITLE
Slapper Not Spaned

### ISSUE THREAD

**Issue by ChaostixZix** [jojoe77777/Slapper#69]
NOTE:
Pocketmine-MP 1.6.2 Dev, Branck api3/blocks

There's no error on console... so i dont know the problem
It says Succes To Spawn Entity, But The Entity Not Spawned

Note : Only Human Entity Type Can Be Spawned

**Comment by ChaostixZix** [comment]
closed?

**Comment by jojoe77777** [comment]
Unable to reproduce. Not much information provided

**Comment by jojoe77777** [comment]
That doesn't tell me what the problem is

**Comment by ChaostixZix** [comment]
the problem is , only Human entity spawned...

**Comment by CyanCreeper** [comment]
I hate when you guys just close the ticket...Just listen to us for once! We cant provide more information BECAUSE THATS LITTERLY WHATS HAPPENING! We cant spawn in any thing! If we do /slapper spawn human IT DOESNT DO ANYTHING... What else do you want?...

**Comment by jojoe77777** [comment]
@CyanCreeper You say humans don't work, @ChaostixZix says only humans work...

**Comment by BrianZP** [comment]
Ahem. Everything is working fine for me.

**Comment by CyanCreeper** [comment]
Ok, sorry once again if I sounded rude again. But, I was very frustrated. When I do /slapper spawn human it does nothing and it pops up in chat saying a unknow error has occured while performing this command,

**Comment by HimbeersaftLP** [comment]
This is a parody of CyanCreeper's previous comment:
I hate it when you guys can't provide enough information...Just listen to the console output for once! You could easily provide much more information by taking a look at the console output BECAUSE THERE AREN'T ANY PROPER ERRORS SHOWN INGAME!

**Comment by discordmelissa** [comment]
Ive tested Slapper on Tesseract MC 1.0.7, Pocketmine 3.0.0-ALPHA5 and Pocketmine 3.0.0-ALPHA2... Only the latest Tesseract version is working on server.pro for me. The only problem is, it will not spawn any entities, and it shows an error message in the in-game chat
