### ISSUE TITLE
Tap and commands not work on slapper

### ISSUE THREAD

**Issue by NycuRO** [jojoe77777/Slapper#7]
I'm tap slapper and not execute commands.

Not work and /slapper id.. and other...

**Comment by dktapps** [comment]
https://github.com/jojoe77777/Slapper/watchers

He is watching to repository... you don't need to ping him. It's annoying.
(Didn't I say this already?)

**Comment by NycuRO** [comment]
@jojoe77777 Fix?

**Comment by jojoe77777** [comment]
Can't reproduce
