### ISSUE TITLE
Error in spawn

### ISSUE THREAD

**Issue by AhmadCraft17** [jojoe77777/Slapper#70]
When I type /slapper spawn human. The server send An unknown error occurred while attempting to perform this command

**Comment by armagadon159753** [comment]
More info plz !!
Send console screen

**Comment by AhmadCraft17** [comment]
06.07 01:01:19 [Server] INFO [Server thread/CRITICAL]: Unhandled exception executing command 'slapper spawn human' in slapper: Class pocketmine\network\mcpe\protocol\AddPlayerPacket not found

**Comment by armagadon159753** [comment]
you dont use PocketMine-MP wath software ?

**Comment by AhmadCraft17** [comment]
I use GenisysPro

**Comment by armagadon159753** [comment]
Have you discord?

**Comment by Sandertv** [comment]
This is an issue that occures because of not using PocketMine-MP. Therefor this is invalid.
