### ISSUE TITLE
NPC keeps disappearing.

### ISSUE THREAD

**Issue by jdongel2004** [jojoe77777/Slapper#74]
I'm using PocketMine 1.6.2!

NPC goes out when I create NPC and go far and come back.

I put Slapper.phar , SlapperRotation.phar , SlapperCache.phar plugins.

**Comment by BrianZP** [comment]
Are you using ClearLag or CyberLagg? If so try removing them and test again.

**Comment by jdongel2004** [comment]
@BrianZP what is ClearLag and CyberLagg? I don't know what is that.  But I use Anvil map.

**Comment by jojoe77777** [comment]
Can't reproduce
