### ISSUE TITLE
'/slapper edit <id> hand <item id>' doesn't update hand item

### ISSUE THREAD

**Issue by MSG100TC** [jojoe77777/Slapper#77]
I tried [/slapper edit (id) hand 267] many times. It only showed "item updated" but nothing happened. 
I even tried many ways to make it work, including relog, server reload, re-installing plugin. But slapper just can't hold things, how to fix this?
Armor worked out fine. But holding this drived me crazy.

**Comment by MSG100TC** [comment]
Still doesn't work

**Comment by dktapps** [comment]
I observe in latest builds that it doesn't immediately update the item in hand, but shows the correct item after relogging into the server.

**Comment by TheRoyalBlock** [comment]
Similarly, editing the skin with the /slapper edit (id) skin command does not apply, even after relogging.

**Comment by MSG100TC** [comment]
Seriously, the thread is 7 months old, has it been fixed?

**Comment by dktapps** [comment]
I fixed this months ago after I commented, but forgot to close this issue.
