### ISSUE TITLE
PocketMine api3/blocks branch is not supported

### ISSUE THREAD

**Issue by NickTehUnicorn** [jojoe77777/Slapper#78]
I'm using PocketMine's api3/blocks branch (because it has all the cool blocks and stuff), and slappers don't work with it. I have SlapBack, SlapperRotation(dev) and Slapper itself (dev branch). Here's what happens (in the video):
https://youtu.be/ZxiOpkPPlds
Human slappers work but none of the others do.
Rotation doesn't work.
SlapBack works.

**Comment by discordmelissa** [comment]
Tesseract is working fine with plugins, the only issue is that it will not spawn. Try Tesseract with the incompatible plugins you need... I downloaded Minecraft PE: 1.0.7 apk on google because that's the latest available Tesseract version for me

**Comment by xXSirGamesXx** [comment]
@NickTehUnicorn im having the same issue.

**Comment by NickTehUnicorn** [comment]
@discordmelissa 
1) Tesseract makes me laugh.
2) Slappers don't work with tesseract.

**Comment by jojoe77777** [comment]
Unable to reproduce, please try updating to the latest versions.
