### ISSUE TITLE
Make it so clear lag does not mistake the "Mobs" (not players) as actual mobs

### ISSUE THREAD

**Issue by austina1212** [jojoe77777/Slapper#8]
What the title says :D

**Comment by jojoe77777** [comment]
https://github.com/jojoe77777/Slapper/blob/master/src/slapper/Main.php#L707-L716 I added code a long time ago to stop that, and as far as I know it still works.

**Comment by austina1212** [comment]
Like I have a mob stacker plugin, and it stacks all the slappers of the same kind (Player or not)

**Comment by jojoe77777** [comment]
That's your mob stacker's fault.
