### ISSUE TITLE
Unsuppprted Pocketmine 3.0.0-ALPHA 5 and one other issue.

### ISSUE THREAD

**Issue by discordmelissa** [jojoe77777/Slapper#80]
I've tried using the Pocketmine version above, because that works for 1.1 and its the latest available on Server.pro
On the other hand, Tesseract will not accept Slappers spawning in the server. I have checked in the CONSOLE, and it says that the pocketmine network folder is not existing and its trying to execute from it. I've tried getting the GITHUB zip file from Tesseract, but the server keeps on crashing.

**Comment by dktapps** [comment]
Tesseract is not supported. Read the README.
