### ISSUE TITLE
update API 3.0.0 ALPHA7

### ISSUE THREAD

**Issue by teracube** [jojoe77777/Slapper#81]
Hi, 

could you please update the plugin on API 3.0.0 ALPHA7
thanks

**Comment by dktapps** [comment]
There is a branch for ALPHA7, but it has not yet been merged because ALPHA7 changes are not yet finalised.

**Comment by teracube** [comment]
thank
upgrade alpha7 would be appreciated if possible ;-)

**Comment by jojoe77777** [comment]
https://github.com/jojoe77777/Slapper/tree/alpha7
