### ISSUE TITLE
Spawning Animals

### ISSUE THREAD

**Issue by mvbenz** [jojoe77777/Slapper#82]
I am running Pocketmine-MP on GameServers.com for my kids and a few of their friends. I have been looking for a plug-in that can spawn animals as the vanilla install doesn't appear to do it. I was happy to find your plug-in as it is one of the few that is compatible with the version they are running:

This server is running PocketMine-MP version 1.6.2dev "Unleashed" (API 3.0.0-ALPHA6)

I loaded the plug-in and use the /slapper spawn pig command and it created a pig but the pig just sat there inanimate. I assume that is not supposed to happen? It did the same thing for other animals also. 

I am not a programmer but am willing to help test if needed.

Thx!

Mike...

**Comment by jojoe77777** [comment]
This plugin is designed to make entities that just stand still, useful for hubs.
