### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheRoyalBlock** [jojoe77777/Slapper#93]
Running the latest source using Devtools to load it from source instead of phar.

I get the following error: 
```
Fatal error: Declaration of slapper\Main::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, $label, array $args) in C:\Users\Royal\Desktop\Locker\Hub\plugins\Slapper-master\src\slapper\Main.php on line 79
 ```

**Comment by dktapps** [comment]
you're using an outdated PM version, and either you've modified it or you've modified Slapper. As seen here https://github.com/jojoe77777/Slapper/blob/master/plugin.yml#L6 this plugin will only load with API 3.0.0-ALPHA7. Therefore this issue is invalid.

**Comment by TheRoyalBlock** [comment]
Oh, it was from this commit... https://github.com/pmmp/PocketMine-MP/commit/46a2e6cbf8f1fd71e632b1d3b4ccc34492683721
mine was from before that, this is meant for after. I dislike that commit, so i just edited this plugin just now to make it compatible with pre- https://github.com/pmmp/PocketMine-MP/commit/46a2e6cbf8f1fd71e632b1d3b4ccc34492683721

**Comment by dktapps** [comment]
and obviously did a poor job of it... don't come to us to fix stuff you broke yourself by doing stupid things.

(and really, how hard is it to add a few typehints? any amateur could do it with some linux `sed`)

**Comment by TheRoyalBlock** [comment]
as I said, I fixed it right after you reminded me of the new api. not my own coding error.

**Comment by jojoe77777** [comment]
> not my own coding error.
> i just edited this plugin

You edited the code and made it crash and you say it's not your coding error?

**Comment by TheRoyalBlock** [comment]
Sorry, I'm not very good at explaining myself.
sequence of events:
I download pocketmine before that plugin-breaker commit
I wait a long time
I download slapper now
I get this error
I post this error
I get dktapps' reply, which triggers my memory of downloading old pocketmine
I edit the plugin
it works
