### ISSUE TITLE
Mobs and Fallingsand don't have tags

### ISSUE THREAD

**Issue by ManiakMCPE** [jojoe77777/Slapper#95]
I am using the latest version of the Slapper plugin and when I create an NPC that is a Mob or Fallingsand it has no tag even if I set the name visibility to always. It works fine with player entities.

**Delete this is if it is a PMMP bug and I'm stupid**

**Comment by jojoe77777** [comment]
Blame Mojang, they messed up nametag visibility again. I'll fix-hack it soon

**Comment by ManiakMCPE** [comment]
How long is soon?

**Comment by jojoe77777** [comment]
Within 5 years
(probably less than 1 week idk)

**Comment by zKoz210** [comment]
@jojoe77777 update to new Skin API

**Comment by dktapps** [comment]
@zKoz210 stop spamming.

**Comment by dktapps** [comment]
maybe a FloatingTextParticle attached to the mob, and override Entity->broadcastMotion() and Entity->broadcastMovement() to move the FTP as well? (problem being that FTP entity ID isn't accessible... hmm)

**Comment by nikoskon2003** [comment]
What if when spawning a falling sand (or any entity that is not human) to spawn a little human with size about 0,000000000....0000001?

**Comment by NGGNewGen** [comment]
TEMP WORKAROUND:
Create a human slapper
Set the tag
Change the size of your slapper to 0
tp it to the desired destination

And the result, Basically floating text :P 
[https://image.ibb.co/hWYXky/Screenshot_16.png](url)

But 1 thing to notice about this is if you break or place a block near the slapper it will fall.
