### ISSUE TITLE
CRASH REPORT

### ISSUE THREAD

**Issue by Shavinda101** [jojoe77777/Slapper#98]
PocketMine-MP [#81dee2f 2017-10-08] Crash Dump Sun Oct 8 12:28:48 EDT 2017

Error: Undefined property: slapper\entities\SlapperHuman::$skinId
File: Slapper_v1.3.6.phar/src/slapper/entities/SlapperHuman
Line: 77
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Slapper v1.3.6

Code:
[68] 			$pk->entityRuntimeId = $entityId;
[69] 			$pk->position = $this->asVector3();
[70] 			$pk->yaw = $this->yaw;
[71] 			$pk->pitch = $this->pitch;
[72] 			$pk->item = $this->getInventory()->getItemInHand();
[73] 			$pk->metadata = $this->dataProperties;
[74] 			$pk->metadata[self::DATA_NAMETAG] = [self::DATA_TYPE_STRING, $this->getDisplayName($player)];
[75] 			$player->dataPacket($pk);
[76] 			$this->inventory->sendArmorContents($player);
[77] 			$player->server->updatePlayerListData($uuid, $entityId, $this->namedtag["MenuName"] ?? "", $this->skinId, $this->skin, [$player]);
[78] 			if($this->namedtag["MenuName"] === "") {
[79] 				$player->server->removePlayerListData($uuid, [$player]);
[80] 			}
[81] 		}
[82] 	}
[83] 
[84] 	public function getDisplayName(Player $player) {
[85] 		$vars = [
[86] 			"{name}" => $player->getName(),
[87] 			"{display_name}" => $player->getName(),

Backtrace:
#0 Slapper_v1.3.6.phar/src/slapper/entities/SlapperHuman(77): pocketmine\error_handler(integer 8, string Undefined property: slapper\entities\SlapperHuman::$skinId, string phar:///home/multicraft/servers/server6529/plugins/Slapper_v1.3.6.phar/src/slapper/entities/SlapperHuman.php, integer 77, array Array())
#1 src/pocketmine/Player(968): slapper\entities\SlapperHuman->spawnTo(pocketmine\Player object)
#2 src/pocketmine/Player(895): pocketmine\Player->doFirstSpawn()
#3 src/pocketmine/level/Level(2388): pocketmine\Player->sendChunk(integer 10, integer 12, pocketmine\network\mcpe\protocol\BatchPacket object)
#4 src/pocketmine/level/Level(2429): pocketmine\level\Level->sendChunkFromCache(integer 10, integer 12)
#5 src/pocketmine/level/format/io/ChunkRequestTask(91): pocketmine\level\Level->chunkRequestCallback(integer 10, integer 12, pocketmine\network\mcpe\protocol\BatchPacket object)
#6 src/pocketmine/scheduler/AsyncPool(164): pocketmine\level\format\io\ChunkRequestTask->onCompletion(pocketmine\Server object)
#7 src/pocketmine/scheduler/ServerScheduler(342): pocketmine\scheduler\AsyncPool->collectTasks()
#8 src/pocketmine/Server(2510): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 275)
#9 src/pocketmine/Server(2257): pocketmine\Server->tick()
#10 src/pocketmine/Server(2136): pocketmine\Server->tickProcessor()
#11 src/pocketmine/Server(1718): pocketmine\Server->start()
#12 src/pocketmine/PocketMine(556): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/multicraft/jar/pocketmine/pmmp/1.2.0-alpha8/PocketMine-MP.phar/, string /home/multicraft/servers/server6529/, string /home/multicraft/servers/server6529/plugins/)
#13 /home/multicraft/jar/pocketmine/pmmp/1.2.0-alpha8/PocketMine-MP.phar(9): include(string phar:///home/multicraft/jar/pocketmine/pmmp/1.2.0-alpha8/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP [#81dee2f 2017-10-08] version: 1.7dev #0 [Protocol 137; API 3.0.0-ALPHA9]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux mc34.vgmc.us 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64
PHP Version: 7.2.0RC2
Zend version: 3.2.0-dev
OS : Linux, linux

Loaded plugins:
HG-PLUS 1.0.0 by POCKETMINE for API(s) 3.0.0-ALPHA9
AutoBroadcastPE 1.0.0 by Vaivez66 for API(s)

eNrtXI1v27iS/1cIt7iX3Fm2ZSe240X6kKZpG2za5pJ0ew91EdASbauRRK0oxfEu+r/fzJCUKCdp
etnsAQ9oF9u1KHI43/Pjh/bPVhElojXxd3ujnXHP74/brZir4ijPZd6a/Nkq1hm8bqWyiALRarcS
oRRfYNPHNBTzKBUhy3KZibxYT5iKeQY/p1ORFlERCTWdnuumt2XC08nkubqK0uMQCM3LOH4dxUgp
W/J80u12lzIR3aSMYaqcz4uuEvm1yJX573C3v9fN4nIRpaprqF5e+51BZ9hBCl2VB13DQNfO33Wn
h24ZzqxnfRQJGB6DzK3JaNRuFTkHnUw+t5712KOobY1G2xOWyeBKFAmQBb2h3i+XPA1jkW9FaSEW
ImfjNlNFHqUL9leUXhH5/9R3m1khQGOM5zlfswP8e2t7G5T5zGdIplZB9zTmaxB9bzjeflA074XK
+Cq9kFuuDjUFJmdfRVDQJP17Jhnv7W7oX7/wXoTydZSr4hzJbxGNwSaNWFyLuHuCf2/1B+PxPZSU
SMPDZZleVdb0e7VS/H67MSoVxUrmV9NpEmTwCEYuZCDj6fQlL4LlKceermQ73+Vqp7+3wRW9nk7p
vcPb61wmhzxYinuYpLl2755rLvOEF91IdonUmfi9FKq44Opqa8//7vSB0/+Qx/EMxPtbtDTc5FyB
qGEJIdY9UOs0OJUy3vKHO3dzqwWcTiM5nW6K6L2Q6aFMslgUkUwbbnhOUeSyMbqfDd353D5vDXb6
G8xUfafTimdQoYxjII+sKO2n481JNOmt/q7fu5/kxvzei4RH6cUyFzx8K3hezAQvKtP0R7s01d59
U/V3N/OafuO9gFRzpfn0e/eN9gfD74w+zWUANUjmhox/Dxl/5I/vIaMKkMgMv50a6Oc7+Lm1u3sf
I5eXgUwhm5ZBsfWSK3EINVOdSB5WBm86bFlEMeSud6DUE7lYOL0eSMlfIc86zGVJknX9Tr/T83gM
Y8YOu967U52XK6I/kuD/T51tNdCqG7CnYHcLU1SUBnEZiq2/QRv3mher03bry7d2S/z9YOdpIAfw
qk1Q04K3gQwFcj8cQ/O0wH+eZ5CZiNr6rEwR4h2HbJ89103H4S8wbLjX7J5JFWESw37FMlLeC65+
Ax+V+WBrGweMes0Ba76q+8ID9fE3iEaQkOte9Ej9+s1+USGSuttCFMfpNTArc8AJ+hk6HKdvARgZ
ZgZNAokoeMgLXhPBp1NtLFApjdm5e8xnJeL5ZPLq4OLg8v3Bu6OLgzdfgI7bfPGv06PL84uz4/dv
2g6XryKVQZ1/zxOx9Tyjir/9habadaaymAIZotoEfa+0FMO6myYaWbl1dT7IE5kfSki8aaGqKWjo
6PYMyqSnMoO5hEYgJ5EqXsHMW8/LMgIMWPlAJUcK3IcFX3yett6JtERhpq0v7J//ZNPWtFV1syDS
eWyzz2buL5qn2gOj+db3ye/v7xP9bfYnjqyd8Q55cpHI63vkaXIwrn30Gz5ad6QH7XP0E70H/6s9
IitncRSweZkGFAEbljWA0mqfGB5bAz+/5rlCb8HG2pzT1p8o+Ldpi+2/YJVEQJlIbrex+8jtHuoZ
Lx8Y9u3nuuPnuuPnuuPnuuPnuuPnuuPnuuPfdt3Rbi1EKnIeI3THmg9YoEGGfX429kMh+nPW7/kj
z+95vfEX0ABqB4Ie+vudUSiuoWlWRnHYmvRgfWByUmviD0btFs8i6Dfo9IDXg5PTtwd70HsRFdDY
+8E/MCDnV3E0wzGdcceHhtIwfBKl5Q1LgsFO53qRBJ1SsUHHx8mGewNQUL8j4lHnZjy8HO4wqLnn
INZFKdi5yCC5sn5/0h8Co+zjxSEJyXRXmAG3aietESr57LAPDX9AzSBRUO1aauhzKZVlAxroIaaH
aqmkUL9v33inJx/PHVXblqY6gXNo4WWxlLlChHX64fDXo4t3x++P0GKkzc9NdUKzSPksFsAdBKZo
t0KRAa84HN4pOS9euQ2Y4GCud4enR/7OdPr2Df6LazyIYnSBD+cXnz6cnbyCppWYwZIMuUVxDspC
vsyhV8BVcXrkyLL55gGZfuPRtfhjOHxiiSxZqBNNfjYafkTWwyXUuTNAnLEbHm7rpox+U8bXPL6K
8iv1xDI6HGBNdtl5UKZPMo9D5YhjGm5J0hTlTgFGjxVAlfk1n05XNPV0WrHwIPcX7y/OytTh3jQ8
4Gsvy6urqEBMqt4dPrExNAe6uv2ICEdKIZznsWpET6PZFad/W5wTwCHAxoc5hi+7EDxp3WOftvs4
fqyILm8AX6nQPyTqsigyBVUMsvyynHUCmXQ125rrbkNeUMt5tEhPZV40KpHT2LQwrMOaKtnbi4VM
A1g6LhxdWN05SvCbj/3m46D5uNN8fLSPVLzt7QGKqoT6Mae5Q5OOtF1HR6RGROOQ6ZYNNVaNtzxL
Y4fRRr2pEID2LpBsKRfLKMCDS776g69aT5sQag5RPw63RjPnFwdnFx9PH9JLzXfXoQJqOYNpZnJ1
eTSfA+50VLPx4oE8chLFh3mksnVf7nUP0oWIJfstCvNIPnFSMWxprn48t/jXyneEo0dXJGCss/tw
Xn88nIjSaB7d4FJRpuJaSUT/H1Lxm4K/fig5wsJCJuuD02M3NdaNrjC7nVHH9/odDX6bhoKJZ/Dv
35sWzSTTqdAMwkzTaYPZB+WtvfStiHEf/a6gNa82Q3fo+XfKzuOojNdPILqbN76jBj3fdLokNh+d
03gsvvI0zCWQc5Ysnl11FbmA1RAgN9wv2NQNqFKV8OPlwZmjwqqpGdbDTn8TpkWwKD3/1/kTR3FF
dzq1rNS/HqGimk+Q97TMxanIExfL1W1NiXc2gelw5/XrXo/9BzvNJa7Ej9M5hG7heg0U2QHlP1tE
+1B1n7CY7j5Rbb3UskynlfDOz0comcYan6vpgMLf8XR9Cz07jZvxOYDFKKwNRz8enY/WgQ3BBLix
oPpHa8a7KMjlS14UsWgI5jY3RRtslsVfeVTIV/DPf51EOOBltGjAbP82DHu0qM4MIKPDZPPpx5Pv
r1HRROKN5kYcNaXOuCiK6Ikt6U7+4zY8v1p/4rlCE7iCOK23gA07E0hWhJdH79+cHJ+/vcekd5jR
v50IHi1vNQ/gPs1u9eNHBH8ri5cx1Ap3S8U2bYq88zDwecJ8Nmw+fh8ZuxDn4WXzUhYzlHA6dWR9
2EfMSb3jH9XZvauoQWfYdIWv8qsUI/zz98Kp6rTrkQCi5tMewzmI8iPobn0bU+rmB3Zxvgsmh7cq
5BMYehNZlshmhS0t0w+aHMvX4ZIXGwiBmjYBQu8ugPCY5OaAkFsSAiKio20FsAPm+x9xHckSMp1n
21v31HVkuf71BFWdyHzD7Vmeg2YAVFrvpP3+TlZd2QB6z+oLHOxQAlRaMLxKM82n6bPzMmUfgoKN
md+f9MeTwQ47enVB28j4PpFFuI8LUtrCn7DTI6ZPUfDlagn8enGkiv0ePvM0lWUaIOal01MeLCNx
LRK8dbEvU+xCJ74ebq8L0tj+gAbGsVx58zhaLIt9OZ/XPXkaJTxujk7kzDYsQPZEhkLPP5c5TF61
6S5LnoeBzIWlm11n5k0YzedRUMbFer9PxOgkoZC5p7Aypgu1j810jghNInQe8Y7T/uuTgwts0r7k
/V6KfG1om6YcPN5OjL87GVcKEE64/5/0B0QvC+kpfm3ZvY7EygtBpRwUub9XaycVxVLkVhGpRIt6
xotNq8w8aEwihXHhEaNav7lQskTdZDy4IimMhaIQmMSLTbIstBLMZREMN+qY8BsPD+6oF7WQmJ1M
5sW+ozXh6QM18E1rHJnijSvPsYW1X4qroKZR0yxQTd2B2wMeDD2qFeYVckMA0VPRHzWDdHDjLQX5
jzatIhqxXKCnVyYQoSogMXkBj8HwnDzQ+psWPMr2d3Y7g93ODiw6dlyVkMT+nj/o22m1EtW+3+vV
nkGae/vxpY9NNzN542FaMvzjcUu1NOyskxijk2HBYAEFZpkTUxSfDPyZNQ6zKGLZxVIowayPMp4L
Bq7BQC4FP3jBAgzEgs2EPZkL4Qe7lRk0tXOZwNg5ktikqvhctJlEv1NIlM1ywa/YGnzJUGPRnIF9
o3lEc0Cc5RDXAOWJ9Huxqgh2QzHnEGuKrWT6j4JhgeM5Q/dPQGQwSLwGERjedtLSr5YiZWW2yHkI
BDpIEm2hyU3wkT3DM26wMjQCLzFPFyVfCIZX+Uh5xnIqgmfwIlhm/EHq1YMPlyIw0jSHAhs2BYu0
s4quokyEEe/IfNHFpy7enrqU88vj8w+Xw8Ge17/EcaTQitSETaHILKYtPdmnJcUvKyTDexsM5DVn
t2C0nKeAHgrQIb0mzRK/wAv8EgUZOIRyEwimrxdhS0Kkddarp51DvqTcztSyLEKJEadvYCJL5l5D
EEslQsvcAWYYhomczm91nWHXEWf/jcFOnSjs7W7GhGHZ1IPPlzCWo/8qCXyZubT5uCHGSgXOCUUW
3IPkBAABPaFch1pr9SsP2JsBc+4UR5QRLC2Qn2FGx0tU4CnI8mzNjH/RAJNBqveuUp59ikD1kJvW
jIchg3SlvRLZxUQHbHEAKFS1GPjiTKBuwAzi95LHaKBFdA19r3lcCrZlpoWCuU3k9ZyQ+QXmCw8s
jBcGJvBez/6+TGZ4gWDO6B4IXv1geBsGQqyje3wEw5D3WnGx3zIH6FSCq+BVkTajHMhM6gWHboNC
EtAgZX5SEKAJbEvKFGILuxjq5+RMIBcEYC5voLoWAlQBYlEgpBV7qGHL0vEc4xg7Yby2WVT8A3RY
5DQuFFjLyUM3RrMtkAIsz/paNySJZ6QFlWBAY63O1yac38RyBjpG0MX0C3DKJCowfSViwWfrAnhi
55qXHs2uM71NByDYKiLeSO8MK6emZE2hSD3zCPwHMprAe6JIZw6JxM6pfQHkKcmTFxJEkRg1qDia
aUGMesQc2nZnjLKwZ5TJC7p4828gBSLV78uA4OkvygAFNyM2TF6r2DL0FINoQ1gE6ahiCue9zRmg
8khSLcNAVThpQDnccFgFow+TQT4KtdtRHw8xCoUhkcLLwFEKAQwqxARyn4a1ZgHoxlQWMBXobpqy
pgKBWQe6zVo4ywfMMlgiaUjndncU32A4UGYmAqykitSD/Gpt67GVEKBRkala2EHPSKu272HKyD7o
Gb4WPJ+BS3jm+hkkBx1/d2qYfAwZMqOYGQWhDfCspLrt8gLIpgTf2G7blHHLOYx36BRMJ0REP6n9
rsM+6GJJT+AhS1nGYcVKBClmlbKafe3OLCPuQdBhr2dlZc9eU5DcSqLkPZpCJdo8l4nNxpqk6eG5
qctWE03+wljytnfc4VQN90AISZcolVX/CYUEpk9qRhZxoYiCMQ022xTCOQAapTt5iCYQH9XUNDFr
exNFe8NKIa+kHrppUSwdiMD0wCYVPZfp2JDir2hAQ/kAr65aHVjkbibEVw4SeIDgNDV3Sx14CL4T
63o6w+ulBHDoiqnCG6rMJDKKVA2BzVudvWaiqqwmPz1zc559h3kiXxdIvc083/F4XUFpaq+w7EAe
2h0aEOrUbVpAYMEMdZY0ptWj8dK45qzD3sJCBxS+D9gbfPvw9GMbxgIXM0hZqygsljrnm3RQTaCX
hBM2qoBGDUIUqcjp3GEHIYTeksfzLiwtNDYKBXihmQym1d4pUzd2nUrvUGsgsKMbjFQEWDxu6zyA
k3+KUkCrIB44lCDnR+zw8TQ9tcijXikguMJBKygURLTM0swzDU3EB6tBMSsX1iWkSbgMS05OTi9u
RFBqGIU5C+/Idaq3Cr2EsFG2zDpRGiEzvpHS9rEB/InnKSZ8ZzQupEyKR0qGSJuFUHxQrLpnwqFY
JGDkAlWa6y+OMPbpCnMK0B8o22qhJwRpUy+a230AN1IsaAaryBV6kbgJRKZn0ti8nnnOIzAEOTxt
NjA5K8CiOIo8DCAe9CAB9HVqmyogbc/1m4pam83KgmQJONqP28If5FwtDd8OoiQ7taEbyoIz2rjL
eaRoSqh36GXzWhSEPFYaQ5HeeVVrw99gshfMR9hqIAmuWMgp7GqFjIzSmFWMXsnpaPHdNYhiXVXw
ooTk0V0ENsBwn0K5U9ZbLBO71pSwpkHF21WgsGsa+tyBPrpS/NqudPF3tY+GLx3TcnAMyI+CF5Na
m0aNBjYSMIfYI/SiMoEGAjSTyiCOMkZjIc7eVUbCD4PMgkeVAnMf5BCFOwO0+4IeEwVL8mXcWViD
6fQ+QkwuG9Pgyiv1hpWlqVlVDd+sGUYfV3oWvb2gtHJwCWaUo6p5iRKqyGH9CTlGV+PERCN92A3A
jZ0HYZecTMeE3nuhzqZ4lMosgwOgWZj6YQZ5etCEZeA811FsFuKNJEcXpIQlSQmYACAoCBMuhigA
WgPVECNoHKidBPcVaeNOg7/aexovapBdFTcNP2dcCWfKLR+qzR1ztVkfXvh3vRBF0Nk21U8JlxcT
URdIHfdBrJkFVHs9JzquVh3tPtXbUlhVKUPhIkYbj8crvlaavqHUMF8DJhnrHSQS0quDtJRZQFlW
UBCkqNf0EIP4MGE73xvOc2gNtRSajlnQVDCP+Xv9eyiQ86RCbwHNhKY4E3NMv7RDinkPDeNQ1jun
DqqwoOIckodOvBHueQncL8nWZpfPgL9qaUG1d04XUyziqPDBvIypo1RFvPYw80WBRm1URHLcVgOH
AcJWcV8lblloRK94IijAdZ5ELFdpwknPd+AQyzkKbRSkm9NqL9BiDLJurr/pucPuaLfa7u/4DeOb
qs/0NykirB1w0+wmOs54GJXKGWpMzm0aB9tVw43D4whYkuiKghvUnv6utKGDIBZcT0bHKe7e1/Er
mtBkNcxl6KYaFEBsAmRKmBGS2WpoQTQNaqqAPfMgZJ+xBVRj5Sqq3kyqddW5rSxTJ1c8or1CULvG
MeCy9iQgtPuFpaBt+gkbP5JiJrMyriiaJwSyt4hPU0pAeP4xMUUSD448ChGFFtQmNGcPVbtf5UQs
uBNmV47WW8EuaZnB8skuKHXMUda0qM+eZwCw7plyok+tgPyuxWk4adVsWnkyiyDMbTdzGKR3Dic2
H+NmJyInptt1IBiXtaF6G/5hpHi4Kb3ZVpWxjXbApQjuXKdcSvREDducUwtYYhluU5muE9xnoMSg
wALKYRs3UEwHVncg9gnt8MUiFwuzfVltE+N6FL/MvbpfNs0XklR384Va1EFmnOE2DfAh3WPiAGkD
/lykQu0ya2x4H+JJCG3Hi1hmiCMA8wJCxk1iBBB20Qf4aw5rdQGGgEKeIpbEbhUmLRVhWZcQM4fa
DlYtYZGrCo0FbA0w9LT1dAc7h7qlqNVqdbea4gjqsrXY0Q1HVGQfESLDTIadieXLvIRQwW29CftM
MBUqcpv2+b5oyrpA1EDJPVcioeweht5XsseutCK466CKsCuVfUUrTlqX4HdlwLBBRw0hzMzEhvnN
8PwW04Cp4PWsE4bHuJP+L6P27t6N3x7cDNr9X/xfQoAxOh9u4dXNALPW/rinE6d+2tndNod64qYA
yEo3ACZ/tg6haDc/u0JPa7aAbKlScbMxCzYHqt/jqBCDjY+49GdkTsssANS4bLbh8VEa8nyj1fzf
OdymMt/gYx7FhdgYOC82PiVbJBsNS0gU+gYKPHxV1W1VfCQrhfrjtz61JDN9/LUhb8GR57DZen56
sqmotNjgOVmDrujjNvOL7eJVmD5+5cY8vNCw29vpjeDn82PwhNlgb7i3uyPErB/64Z4IR3u9/mw8
46I/GM3649G873NoZ8+B9umS1Ij3ZPqNI9xLqmH0fSiJpmXH/wfIzQbDZiuTvr2rPjg8E3Oz8bah
hWUiN5SraE51h8xRs62QVyKFwrhhvk+wqoF8RFwO6OuTNafjZyvUH1GmP03Z7fitb9/+F/sp4tw=
===END CRASH DUMP===

**Comment by dktapps** [comment]
outdated version

**Comment by Shavinda101** [comment]
dktapps I can't seem to get the version that is updated. Would you mind sending it to me here: cyancreeper31@gmail.com Thanks.

**Comment by Shavinda101** [comment]
Also, do you know any other gamemode plugins?
